"""изменениа модель TradeLog

Revision ID: 4d10040c4ce5
Revises: 06fc37dab532
Create Date: 2025-06-21 20:00:58.358385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d10040c4ce5'
down_revision: Union[str, None] = '06fc37dab532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], No ne] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_logs', sa.Column('order_id', sa.String(), nullable=True))
    op.create_index('idx_order_id', 'trade_logs', ['order_id'], unique=True)
    op.create_index('idx_symbol_side', 'trade_logs', ['symbol', 'side'], unique=False)
    op.create_index('idx_timestamp', 'trade_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_trade_logs_order_id'), 'trade_logs', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_logs_order_id'), table_name='trade_logs')
    op.drop_index('idx_timestamp', table_name='trade_logs')
    op.drop_index('idx_symbol_side', table_name='trade_logs')
    op.drop_index('idx_order_id', table_name='trade_logs')
    op.drop_column('trade_logs', 'order_id')
    # ### end Alembic commands ###
